package by.nikita.web.controller.command;
/**
 * The {@code CommandName} class represents command name.
 *
 * @author Belyaev Nikita
 * @version 1.0
 */
public enum CommandName {
    REGISTRATION,
    LOGINATION,
    GOTOMAININDEXPAGE,
    CREATENEWUSER,
    LOGOUT,
    GOTOHOMEPAGE,
    GOTOBLOCKEDPAGE,
    CREATENEWBOOK,
    GOTOERRORPAGE,
    BLOCKUSERCOMMAND,
    UNBLOCKUSERCOMMAND,
    DELETEUSERCOMMAND,
    GOTOBOOKPAGE,
    GOTOLOGINPAGE,
    CHANGELANGUAGE,
    GOTOMAINBOOKPAGE,
    BUYBOOKUSER,
    CREATENEWCOMMENT,
    DELETEBOOKCOMMAND,
    BLOCKBOOKCOMMAND,
    UNBLOCKBOOKCOMMAND,
    UPDATEBALANCECOMMAND,
    UPDATEUSERINFOCOMMAND,
    FINDBYNAMECOMMAND,
    GOTOVIEWUSERCOMMAND,
    VIEWALLUSERSCOMMAND,
    GOTOLIBRARYPAGE,
    SORTBOOKCOMMAND,
    READBOOKCOMMAND,
    GOTOTEXTPAGE,
    SEEPROFILECOMMAND,
    REDACTBOOKCOMMAND,
    GOTOREDACTBOOKPAGE,
    UPDATEBOOKINFO,
    GOTOAUTHORPAGE,
    BLOCKCOMMENTCOMMAND,
    UNBLOCKCOMMENTCOMMAND,
    CHOOSELOCALECOMMAND,
    FINDBYGENRECOMMAND,


}
